---
name: 'Run Go Tests'
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.19.4
  GO_WORKING_DIRECTORY: '.'
  TEST_FILE: mockokta_test.go

jobs:
  go-tests:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify dependencies
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go mod verify

      - name: Build
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go build -v ./...

      - name: Run go vet
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go vet ./...

      - name: Install staticcheck
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: staticcheck ./...

      - name: Install golint
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: golint ./...

      - name: Run tests
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: go test -race -vet=off -v ./...

